export const NIGERIAN_UNIVERSITIES = [{
        id: "unilag",
        name: "University of Lagos (UNILAG)",
        state: "Lagos",
        type: "Federal",
        courses: [
            { id: "unilag-1", name: "B.Sc. Computer Science", faculty: "Faculty of Science", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math/Biology." },
            { id: "unilag-2", name: "Medicine and Surgery (MBBS)", faculty: "College of Medicine", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology (1 sitting)." },
            { id: "unilag-3", name: "Bachelor of Laws (LL.B)", faculty: "Faculty of Law", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Arts/Social Sciences." },
            { id: "unilag-4", name: "B.Sc. Accounting", faculty: "Faculty of Management Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Economics, and 2 commercial subjects." },
            { id: "unilag-5", name: "B.Sc. Finance", faculty: "Faculty of Management Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Economics, and 2 commercial subjects." },
            { id: "unilag-6", name: "B.Sc. Nursing Science", faculty: "College of Medicine", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilag-7", name: "B.Eng. Mechanical Engineering", faculty: "Faculty of Engineering", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "unilag-8", name: "B.Eng. Electrical & Electronics Engineering", faculty: "Faculty of Engineering", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "unilag-9", name: "B.Eng. Civil & Environmental Engineering", faculty: "Faculty of Engineering", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "unilag-10", name: "B.Sc. Architecture", faculty: "Faculty of Environmental Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Fine Arts/Technical Drawing, Economics." },
            { id: "unilag-11", name: "B.Sc. Mass Communication", faculty: "Faculty of Social Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Lit-in-English, Govt, Economics." },
            { id: "unilag-12", name: "B.Sc. Economics", faculty: "Faculty of Social Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Geography." },
            { id: "unilag-13", name: "B.Sc. Psychology", faculty: "Faculty of Social Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Biology, and 2 Social Sciences." },
            { id: "unilag-14", name: "B.Sc. Biochemistry", faculty: "Faculty of Science", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilag-15", name: "Doctor of Pharmacy (Pharm.D)", faculty: "Faculty of Pharmacy", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." }
        ]
    },
    {
        id: "ui",
        name: "University of Ibadan (UI)",
        state: "Oyo",
        type: "Federal",
        courses: [
            { id: "ui-1", name: "Medicine and Surgery (MBBS)", faculty: "College of Medicine", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology (1 sitting)." },
            { id: "ui-2", name: "B.Sc. Computer Science", faculty: "Faculty of Science", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology/Further Math." },
            { id: "ui-3", name: "Bachelor of Laws (LL.B)", faculty: "Faculty of Law", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Social Sciences." },
            { id: "ui-4", name: "B.Sc. Economics", faculty: "Faculty of the Social Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Economics, and 2 Social Sciences." },
            { id: "ui-5", name: "B.Sc. Political Science", faculty: "Faculty of the Social Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Government/History, and 2 Arts/Social Sciences." },
            { id: "ui-6", name: "B.Eng. Agricultural & Environmental Engineering", faculty: "Faculty of Technology", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology/Agric." },
            { id: "ui-7", name: "B.Eng. Mechanical Engineering", faculty: "Faculty of Technology", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "ui-8", name: "B.Eng. Electrical & Electronic Engineering", faculty: "Faculty of Technology", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "ui-9", name: "B.Sc. Microbiology", faculty: "Faculty of Science", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "ui-10", name: "B.Sc. Physiology", faculty: "Faculty of Basic Medical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "ui-11", name: "B.Sc. Veterinary Medicine", faculty: "Faculty of Veterinary Medicine", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "ui-12", name: "B.A. English Language", faculty: "Faculty of Arts", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Arts subjects." },
            { id: "ui-13", name: "B.A. Theatre Arts", faculty: "Faculty of Arts", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Arts subjects." },
            { id: "ui-14", name: "B.Sc. Human Nutrition & Dietetics", faculty: "Faculty of Basic Medical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "ui-15", name: "B.Sc. Geology", faculty: "Faculty of Science", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology/Geography." }
        ]
    },
    {
        id: "abu",
        name: "Ahmadu Bello University (ABU, Zaria)",
        state: "Kaduna",
        type: "Federal",
        courses: [
            { id: "abu-1", name: "B.Sc. Computer Science", faculty: "Faculty of Physical Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology/Geography." },
            { id: "abu-2", name: "B.Eng. Electrical Engineering", faculty: "Faculty of Engineering", jambCutoff: 190, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "abu-3", name: "B.Sc. Architecture", faculty: "Faculty of Environmental Design", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Fine Arts/Technical Drawing, Geography." },
            { id: "abu-4", name: "Doctor of Pharmacy (Pharm.D)", faculty: "Faculty of Pharmaceutical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "abu-5", name: "Medicine and Surgery (MBBS)", faculty: "Faculty of Clinical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "abu-6", name: "Bachelor of Laws (LL.B Commercial Law)", faculty: "Faculty of Law", jambCutoff: 190, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, Govt, Economics." },
            { id: "abu-7", name: "B.Eng. Chemical Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "abu-8", name: "B.Eng. Civil Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Technical Drawing." },
            { id: "abu-9", name: "B.Sc. International Studies", faculty: "Faculty of Social Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Govt, History, Literature." },
            { id: "abu-10", name: "B.Sc. Business Administration", faculty: "Faculty of Administration", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "abu-11", name: "B.Sc. Public Administration", faculty: "Faculty of Administration", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Govt, Economics, History." },
            { id: "abu-12", name: "B.Sc. Mass Communication", faculty: "Faculty of Social Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Lit-in-English, Govt, Economics." },
            { id: "abu-13", name: "B.Sc. Biochemistry", faculty: "Faculty of Life Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "abu-14", name: "Doctor of Veterinary Medicine (DVM)", faculty: "Faculty of Veterinary Medicine", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "abu-15", name: "B.Sc. Quantity Surveying", faculty: "Faculty of Environmental Design", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Economics, Geography." }
        ]
    },
    {
        id: "unn",
        name: "University of Nigeria, Nsukka (UNN)",
        state: "Enugu",
        type: "Federal",
        courses: [
            { id: "unn-1", name: "Medicine and Surgery (MBBS)", faculty: "Faculty of Medical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unn-2", name: "B.Eng. Civil Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Technical Drawing." },
            { id: "unn-3", name: "B.N.Sc. Nursing Science", faculty: "Faculty of Health Sciences & Tech", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unn-4", name: "Bachelor of Laws (LL.B)", faculty: "Faculty of Law", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Social Sciences." },
            { id: "unn-5", name: "B.Sc. Biochemistry", faculty: "Faculty of Biological Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unn-6", name: "B.Sc. Computer Science", faculty: "Faculty of Physical Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology/Further Math." },
            { id: "unn-7", name: "B.Eng. Mechanical Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "unn-8", name: "B.Eng. Electronic Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "unn-9", name: "B.Pharm. Pharmacy", faculty: "Faculty of Pharmaceutical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unn-10", name: "B.Sc. Accountancy", faculty: "Faculty of Business Administration", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "unn-11", name: "B.Sc. Marketing", faculty: "Faculty of Business Administration", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "unn-12", name: "B.Sc. Mass Communication", faculty: "Faculty of Arts", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Lit-in-English, Govt, Economics." },
            { id: "unn-13", name: "B.Sc. Medical Rehabilitation", faculty: "Faculty of Health Sciences & Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unn-14", name: "B.Sc. Medical Radiography", faculty: "Faculty of Health Sciences & Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unn-15", name: "B.Sc. Microbiology", faculty: "Faculty of Biological Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." }
        ]
    },
    {
        id: "oau",
        name: "Obafemi Awolowo University (OAU)",
        state: "Osun",
        type: "Federal",
        courses: [
            { id: "oau-1", name: "B.Sc. Computer Science with Mathematics", faculty: "Faculty of Science", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "oau-2", name: "Medicine and Surgery (MBBS)", faculty: "Faculty of Health Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "oau-3", name: "Bachelor of Laws (LL.B)", faculty: "Faculty of Law", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Arts/Social Sciences." },
            { id: "oau-4", name: "B.Sc. International Relations", faculty: "Faculty of Administration", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Govt, History, Literature." },
            { id: "oau-5", name: "B.Sc. Architecture", faculty: "Faculty of Environmental Design", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Fine Arts/Technical Drawing, Geography." },
            { id: "oau-6", name: "B.Sc. Estate Management", faculty: "Faculty of Environmental Design", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Economics, Geography, Physics." },
            { id: "oau-7", name: "B.Eng. Computer Engineering", faculty: "Faculty of Technology", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "oau-8", name: "B.Eng. Mechanical Engineering", faculty: "Faculty of Technology", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "oau-9", name: "B.Ch.D Dental Surgery", faculty: "Faculty of Dentistry", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "oau-10", name: "B.Sc. Management & Accounting", faculty: "Faculty of Administration", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "oau-11", name: "B.Pharm. Pharmacy", faculty: "Faculty of Pharmacy", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "oau-12", name: "B.Sc. Nursing Science", faculty: "Faculty of Health Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "oau-13", name: "B.A. Dramatic Arts", faculty: "Faculty of Arts", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Arts subjects." },
            { id: "oau-14", name: "B.Sc. Geology", faculty: "Faculty of Science", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Geography." },
            { id: "oau-15", name: "B.Sc. Microbiology", faculty: "Faculty of Science", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." }
        ]
    },
    {
        id: "futa",
        name: "Federal University of Technology, Akure (FUTA)",
        state: "Ondo",
        type: "Federal",
        courses: [
            { id: "futa-1", name: "B.Tech. Software Engineering", faculty: "School of Computing", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math/Biology." },
            { id: "futa-2", name: "B.Tech. Computer Science", faculty: "School of Computing", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "futa-3", name: "B.Tech. Cybersecurity", faculty: "School of Computing", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "futa-4", name: "B.Tech. Information Technology", faculty: "School of Computing", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "futa-5", name: "B.Eng. Mechanical Engineering", faculty: "School of Engineering & Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "futa-6", name: "B.Eng. Electrical & Electronics Engineering", faculty: "School of Engineering & Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "futa-7", name: "B.Eng. Civil Engineering", faculty: "School of Engineering & Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Technical Drawing." },
            { id: "futa-8", name: "B.Eng. Metallurgical & Materials Engineering", faculty: "School of Engineering & Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "futa-9", name: "B.Tech. Architecture", faculty: "School of Environmental Technology", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Technical Drawing, Economics." },
            { id: "futa-10", name: "B.Tech. Quantity Surveying", faculty: "School of Environmental Technology", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Economics, Geography." },
            { id: "futa-11", name: "B.Tech. Estate Management", faculty: "School of Environmental Technology", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Geography, Physics." },
            { id: "futa-12", name: "B.Tech. Biochemistry", faculty: "School of Life Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "futa-13", name: "B.Tech. Industrial Chemistry", faculty: "School of Physical Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "futa-14", name: "B.Tech. Meteorology", faculty: "School of Earth & Mineral Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Geography." },
            { id: "futa-15", name: "B.Tech. Food Science & Technology", faculty: "School of Agriculture & Agric Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." }
        ]
    },
    {
        id: "covenant",
        name: "Covenant University (CU)",
        state: "Ogun",
        type: "Private",
        courses: [
            { id: "cu-1", name: "B.Sc. Computer Science", faculty: "College of Science & Technology", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math/Biology." },
            { id: "cu-2", name: "B.Sc. Management Information System (MIS)", faculty: "College of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, and 2 commercial subjects." },
            { id: "cu-3", name: "B.Sc. Mass Communication", faculty: "College of Leadership Development", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Lit-in-English, Govt, Economics." },
            { id: "cu-4", name: "B.Sc. Accounting", faculty: "College of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "cu-5", name: "B.Sc. Banking and Finance", faculty: "College of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "cu-6", name: "B.Sc. International Relations", faculty: "College of Leadership Development", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Govt, History, Literature." },
            { id: "cu-7", name: "B.Eng. Computer Engineering", faculty: "College of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "cu-8", name: "B.Eng. Information & Communication Engineering", faculty: "College of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "cu-9", name: "B.Eng. Mechanical Engineering", faculty: "College of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "cu-10", name: "B.Eng. Civil Engineering", faculty: "College of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "cu-11", name: "B.Sc. Architecture", faculty: "College of Science & Technology", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Technical Drawing, Economics." },
            { id: "cu-12", name: "B.Sc. Economics", faculty: "College of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Geography." },
            { id: "cu-13", name: "B.Sc. Biochemistry", faculty: "College of Science & Technology", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "cu-14", name: "B.Sc. Industrial Physics", faculty: "College of Science & Technology", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "cu-15", name: "B.Sc. Policy & Strategic Studies", faculty: "College of Leadership Development", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Govt, History, Economics." }
        ]
    },
    {
        id: "lasu",
        name: "Lagos State University (LASU)",
        state: "Lagos",
        type: "State",
        courses: [
            { id: "lasu-1", name: "Bachelor of Laws (LL.B)", faculty: "Faculty of Law", jambCutoff: 195, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Social Sciences." },
            { id: "lasu-2", name: "B.Sc. Computer Science", faculty: "Faculty of Science", jambCutoff: 190, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "lasu-3", name: "Medicine and Surgery (MBBS)", faculty: "LASUCOM (College of Medicine)", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "lasu-4", name: "B.Sc. Nursing Science", faculty: "LASUCOM (College of Medicine)", jambCutoff: 190, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "lasu-5", name: "B.Sc. International Relations", faculty: "Faculty of Social Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Govt, History, Economics." },
            { id: "lasu-6", name: "B.Sc. Mass Communication", faculty: "School of Communication", jambCutoff: 190, olevelReqs: "5 O me level credits: English, Math, Lit-in-English, Govt, Economics." },
            { id: "lasu-7", name: "B.Sc. Accounting", faculty: "Faculty of Management Sciences", jambCutoff: 190, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "lasu-8", name: "B.Sc. Business Administration", faculty: "Faculty of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "lasu-9", name: "B.Sc. Public Administration", faculty: "Faculty of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Govt, Economics, History." },
            { id: "lasu-10", name: "B.Eng. Mechanical Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "lasu-11", name: "B.Eng. Electronics & Computer Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "lasu-12", name: "B.Sc. Biochemistry", faculty: "Faculty of Science", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "lasu-13", name: "B.Sc. Microbiology", faculty: "Faculty of Science", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "lasu-14", name: "B.Sc. Economics", faculty: "Faculty of Social Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Geography." },
            { id: "lasu-15", name: "B.Sc. Sociology", faculty: "Faculty of Social Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Govt, History, Economics." }
        ]
    },
    {
        id: "unilorin",
        name: "University of Ilorin (UNILORIN)",
        state: "Kwara",
        type: "Federal",
        courses: [
            { id: "unilorin-1", name: "Medicine and Surgery (MBBS)", faculty: "College of Health Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilorin-2", name: "B.Sc. Computer Science", faculty: "Faculty of Communication & Info Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilorin-3", name: "Bachelor of Laws (LL.B)", faculty: "Faculty of Law", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Social Sciences." },
            { id: "unilorin-4", name: "B.Sc. Mass Communication", faculty: "Faculty of Communication & Info Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Lit-in-English, Govt, Economics." },
            { id: "unilorin-5", name: "B.Sc. Accounting", faculty: "Faculty of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "unilorin-6", name: "B.Eng. Mechanical Engineering", faculty: "Faculty of Engineering & Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "unilorin-7", name: "B.Eng. Biomedical Engineering", faculty: "Faculty of Engineering & Tech", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilorin-8", name: "B.Pharm. Pharmacy", faculty: "Faculty of Pharmaceutical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilorin-9", name: "B.Sc. Nursing Science", faculty: "College of Health Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilorin-10", name: "B.Sc. Finance", faculty: "Faculty of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "unilorin-11", name: "B.Sc. Economics", faculty: "Faculty of Social Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Geography." },
            { id: "unilorin-12", name: "B.Sc. Microbiology", faculty: "Faculty of Life Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilorin-13", name: "B.Sc. Biochemistry", faculty: "Faculty of Life Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilorin-14", name: "B.Sc. Information Technology", faculty: "Faculty of Communication & Info Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "unilorin-15", name: "B.Sc. Telecommunication Science", faculty: "Faculty of Communication & Info Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." }
        ]
    },
    {
        id: "uniben",
        name: "University of Benin (UNIBEN)",
        state: "Edo",
        type: "Federal",
        courses: [
            { id: "uniben-1", name: "Medicine and Surgery (MBBS)", faculty: "School of Medicine", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "uniben-2", name: "Doctor of Pharmacy (Pharm.D)", faculty: "Faculty of Pharmacy", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "uniben-3", name: "Bachelor of Laws (LL.B)", faculty: "Faculty of Law", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Lit-in-English, Math, and 2 Social Sciences." },
            { id: "uniben-4", name: "B.Sc. Computer Science", faculty: "Faculty of Physical Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "uniben-5", name: "B.Eng. Petroleum Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "uniben-6", name: "B.Eng. Chemical Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "uniben-7", name: "B.Eng. Electrical & Electronics Engineering", faculty: "Faculty of Engineering", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Further Math." },
            { id: "uniben-8", name: "B.Sc. Nursing Science", faculty: "School of Basic Medical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "uniben-9", name: "B.Sc. Accounting", faculty: "Faculty of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "uniben-10", name: "B.Sc. Banking and Finance", faculty: "Faculty of Management Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Commerce." },
            { id: "uniben-11", name: "B.Sc. Economics", faculty: "Faculty of Social Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Economics, Govt, Geography." },
            { id: "uniben-12", name: "B.Sc. Political Science", faculty: "Faculty of Social Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Govt, History, Literature." },
            { id: "uniben-13", name: "B.Sc. Medical Laboratory Science", faculty: "School of Basic Medical Sciences", jambCutoff: 200, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "uniben-14", name: "B.Sc. Biochemistry", faculty: "Faculty of Life Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." },
            { id: "uniben-15", name: "B.Sc. Microbiology", faculty: "Faculty of Life Sciences", jambCutoff: 180, olevelReqs: "5 O'Level credits: English, Math, Physics, Chemistry, Biology." }
        ]
    }
];